version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/shudai/Desktop/inception/srcs/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/shudai/Desktop/inception/srcs/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
      image:  nginx:42
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
        - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
      image:  wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
      image:  mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
